blacklistedOres = []
spawnWithGuideBook = true
respawnWithGuideBook = true
disableFuelTooltips = true
disableItemTagTooltips = true
newVersionMessage = true
enableHatchPlacementOverlay = true
colorWaterLava = true
enableDebugCommands = false
enableAe2Integration = true
generateOres = true
